import re
import fileinput

def test(w2v_model):
    with open('Data/1000Words.txt', 'r') as infile, open('Data/testresult2.txt', 'w') as outfile:
        for line in infile:
            word = line.rstrip('\n')
            outfile.write('Word:' + word+'\n')
            list = w2v_model.wv.most_similar(word, topn=5)
            outfile.write('\n'.join('%s %s' % x for x in list))
            outfile.write('\n\n')
    cleantest('Data/testresult.txt')


def cleantest(file):
    regex = re.compile('[^a-zA-Z]')
    for line in fileinput.input(file, inplace=True):
        # fileinput.input() will write any output generated by print() to file
        print(regex.sub(' ', line))

