name: Lint and test

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: python -m pip install --upgrade pip && pip install -r requirements.txt && pip install pylint-runner 
    - name: Run Pylint
      run: pylint_runner
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
      run: pip install -r tests/requirements.txt
      run: python -m spacy download en_core_web_sm
    - name: Run Pylint
      run: pylint_runner
      
