name: Lint and test

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test with pytest
        run: |
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
          pytest
  
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@test
    
