name: Lint and test

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  tests:
    - name: Python Pylin GitHub Action
    uses: fylein/python-pytest-github-action@v1
    with:
      args: pip3 install -r requirements.txt && pip3 install -r tests/requirements.txt && python3 -m spacy download en_core_web_sm && pytest test/unit
  
  
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint-runner
    - name: Run Pylint
      run: |
        pylint_runner
