name: Lint and test

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  tests:
    - name: Python Pylin GitHub Action
    uses: fylein/python-pytest-github-action@v1
    with:
      args: pip3 install -r requirements.txt && pip3 install -r tests/requirements.txt && pytest test/unit
  
  
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@test
    
