name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: python -m pip install --upgrade pip && pip install -r requirements.txt && pip install -r tests/requirements.txt
      - name: Install space small web model
        run: python -m spacy download en_core_web_sm
      - name: Run test
        run: pytest
